name: Digger Terragrunt Drift Detection

on:  
  workflow_dispatch:
  schedule: ## Schedule the job to run at 12.am once a week
    - cron: '0 0 * * 0'

jobs:
  detect-drift:
    runs-on: ubuntu-latest
    permissions:    
      id-token: write
    steps:
    - name: digger drift detection
      uses: diggerhq/digger@v0.4.8
      with:
        mode: drift-detection
        setup-aws: true
        aws-role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: us-east-1
        setup-terragrunt: true
        terragrunt-version: 0.52.4
        drift-detection-slack-notification-url: ${{ secrets.DRIFT_DETECTION_SLACK_NOTIFICATION }}
        no-backend: true
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEV_ACCOUNT_ID: ${{ secrets.DEV_ACCOUNT_ID }}
        DEV_ROLE: ${{ secrets.DEV_ROLE }}
        STAGING_ACCOUNT_ID: ${{ secrets.STAGING_ACCOUNT_ID }}
        STAGING_ROLE: ${{ secrets.STAGING_ROLE }}
        PRODUCTION_ACCOUNT_ID: ${{ secrets.PRODUCTION_ACCOUNT_ID }}
        PRODUCTION_ROLE: ${{ secrets.PRODUCTION_ROLE }}