name: Digger Terragrunt Action

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
    if: contains(github.event.comment.body, 'digger')
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:    
      contents: write      # required to merge PRs
      id-token: write      # This is required for aws oidc connection
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - name: digger run
        uses: diggerhq/digger@v0.2.0
        with:
          setup-aws: true
          aws-role-to-assume: ${{ secrets.STAGING_ROLE }}
          aws-region: us-east-1
          setup-terragrunt: true
          terragrunt-version: 0.52.4
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEV_ACCOUNT_ID: ${{ secrets.STAGING_ACCOUNT_ID }}
          DEV_ROLE: ${{ secrets.STAGING_ROLE }}
          STAGING_ACCOUNT_ID: ${{ secrets.STAGING_ACCOUNT_ID }}
          STAGING_ROLE: ${{ secrets.STAGING_ROLE }}
          PRODUCTION_ACCOUNT_ID: ${{ secrets.PRODUCTION_ACCOUNT_ID }}
          PRODUCTION_ROLE: ${{ secrets.PRODUCTION_ROLE }}
